version: "1"
project:
  name: ${scm.git.repo}
  branch: ${scm.git.branch}
  revision:
    name: ${scm.git.commit}
    date: ${scm.git.commit.date}
capture:
  fileSystem:
    javascript:
      extensions: [js, ts]
      files:
        - directory: ${project.projectDir}
        - excludeRegex: node_modules|bower_components|vendor|test|spec|.git
    ruby:
      files:
        - directory: ${project.projectDir}
        - excludeRegex: node_modules|bower_components|vendor|test|spec|.git
    python:
      files:
        - directory: ${project.projectDir}
        - excludeRegex: node_modules|bower_components|vendor|test|spec|.git
    php:
      files:
        - directory: ${project.projectDir}
        - excludeRegex: node_modules|bower_components|vendor|test|spec|.git
    java:
      files:
        - directory: ${project.projectDir}
        - excludeRegex: node_modules|bower_components|vendor|test|spec|.git
analyze:
  mode: central
  coverity:
    cov-analyze:
      - --disable-default
      - --security
      - --enable-audit-mode
      - --webapp-security
    usebudaforjavadotnet: disable
install:
  coverity:
    version: default
serverUrl: https://contentful.polaris.synopsys.com
