name: "Synopsys Polaris Security Testing"
description: "Run Coverity SAST via the Polaris platform and provide feedback within GitHub pull requests"
author: "Synopsys Inc"
inputs:
  github_token:
    description: "Your GitHub token"
    required: true
  polaris_url:
    description: "The URL of the Polaris server to be referenced API calls"
    required: true
  polaris_access_token:
    description: "An access token to support API calls"
    required: true
  polaris_command:
    description: 'Command line to pass to the Polaris CLI, will default to "analyze -w"'
    required: false
    default: "analyze -w"
  debug:
    description: "Enable verbose debugging mode"
    required: false
    default: "false"
  diagnostic:
    description: "Enable diagonstic build artifacts"
    required: false
    default: "false"
  security_gate_filters:
    description: "Enable security gate"
    required: false
  fail_on_error:
    description: |
      Exit code when errors are found [true,false]
      Default is `false`.
    default: "false"
    required: false
  skip_run:
    description: "Skip execution of the Polaris CLI command, assume it has been run manually"
    required: false
  report_url:
    description: "URL to report false positives"
    required: false

# runs:
#   using: "composite"
#   steps:
#     - name: Run Polaris scan
#       id: polaris_scan
#       uses: docker://ghcr.io/contentful/polaris-action:docker-image
#       env:
#         POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
#       with:
#         entrypoint: node index.js

runs:
  using: docker
  image: docker://ghcr.io/contentful/polaris-action:docker-image
  env:
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_POLARIS_URL: ${{ inputs.polaris_url }}
    INPUT_POLARIS_ACCESS_TOKEN: ${{ inputs.polaris_access_token }}
    INPUT_POLARIS_COMMAND: ${{ inputs.polaris_command }}
    INPUT_DEBUG: ${{ inputs.debug }}
    INPUT_DIAGNOSTIC: ${{ inputs.diagnostic }}
    INPUT_SECURITY_GATE_FILTERS: ${{ inputs.security_gate_filters }}
    INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
    INPUT_SKIP_RUN: ${{ inputs.skip_run }}
    INPUT_REPORT_URL: ${{ inputs.report_url }}
    DOCKER_USERNAME: ${{ inputs.actor }}
    DOCKER_PASSWORD: ${{ inputs.GITHUB_TOKEN }}
    DOCKER_REGISTRY: ghcr.io
